[build]
  command = "gatsby build"
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/secret"
  to = "/secret"
  status = 200
  force = true
  conditions = { Role = ["user"] }

[[redirects]]
  from = "/secret"
  to = "/login"
  status = 401
  force = true
